# Site
name: 'The BioDataScientist'
description: 'Data science | Ecological questions'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/blog'
email: 'aline.fquadros@outlook.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:

    aline:
      name:           Aline
      site:           https://alinequadros.github.io/blog
      avatar:         /assets/images/avatar.png
      bio:            "Data-scientist & biologist"
      email:          aline.fquadros@outlook.com
      twitter:        https://twitter.com/aline_quadros

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: aline
      avatar: /assets/images/avatar.png

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 15



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
